language: java
jdk: openjdk8
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - mvn cobertura:cobertura coveralls:report
