language: java
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
install: mvn install -Dgpg.skip=true
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
    - mvn cobertura:cobertura coveralls:report
